### ISSUE TITLE
VST3 cannot be opened on MacOS

### ISSUE THREAD

**Issue by dev-tb** [Dimethoxy/Plasma#6] opened 2024-04-15 12:46 UTC
Hello, I stumbled upon your plugin while browsing online.
When I still the plugin on mac in the vst3 folder and open my DAW, I get the error the file/developer cannot be identified.
Common solutions do not seem to work: sudo xattr -rd com.apple.quarantine "~/Library/Audio/Plug-Ins/VST3/Plasma.vst3"

Any tips?

**Comment by Lunix-420** [comment] 2024-04-15 13:11
Thanks for letting me know.

The issue is most likely that I didn't pay Apple $100 for a developer account to be able to notarize the app.

You can 100% run the app somehow anyway, I’m just not exactly sure how. You could ofc just disable the gatekeeper entirely, which I can’t really recommend.

I’m gonna try to figure out a step-by-step solution for this problem later and add it to the README.md

Could you tell me which version of macOS and which architecture (Intel or Apple Silicon) you are on?

I think I will also just finally pay Apple for the developer account to get rid of this problem entirely, which means I will most likely post an updated version without this issue in a couple of weeks.

**Comment by dev-tb** [comment] 2024-04-15 13:30
Thanks for your quick reply. I'm currently on MacOS 14.3.1 with a Apple M1 chip and will definetly be donating if I can get this to work and help you cover the cost of a developer account.

**Comment by Lunix-420** [comment] 2024-04-15 22:51
I experimented a bit inside a VM and found that using xattr definitely works. If it didn't work for you, it might be due to the use of quotation marks and ~ for the path.

Here's my exact method:
- Open the folder containing the VST file in Finder
- Open Terminal
- Type the following command: ```sudo xattr -rd com.apple.quarantine``` (Note: Do not hit enter yet)
- Ensure there is a space after "quarantine"
- Drag and drop the VST file into the Terminal, its path should now appear in the Terminal
- Hit enter

This method worked flawlessly on my VM. I'd appreciate your feedback on whether it works for you.

Additionally, I've now enrolled in the Apple Developer Program and already paid the fee. However, it may take them up to two weeks to set it up. Once it's ready, I'll work on posting an updated version that should work seamlessly.

**Comment by dev-tb** [comment] 2024-04-16 09:58
Thanks for your reply. I've tried your suggestion but it didn't work for me. It might be that because I've already opened the file, macOS doesn't accept the command. I made sure the location is being scanned by my DAW and also made sure there aren't any VSTs on its blocklist. I also rebooted my machine and run the command again.

Guess I'll have to wait till the account has been approved. In the mean time I'm already spreading the word to some friends about this project :).

**Comment by Lunix-420** [comment] 2024-04-16 22:30
I'm not entirely sure why that's happening, but I'm sure that code signing will resolve it. 
Also, thanks for telling your friends about Plasma!

I'll make sure to update here as soon as Apple sends me the approval email.

**Comment by dev-tb** [comment] 2024-04-28 08:27
Hi! Any news on the Mac version? I tried the windows version and got really good results! Definitely something I will be using in my kickchains if Mac version (which I work on the most) will be working!

**Comment by Lunix-420** [comment] 2024-04-28 18:25
Sorry, but I haven't received the email from Apple yet. 

From my research, I discovered that they typically respond within 48 hours to people from the US. However, it seems that response times of 2 weeks or longer are normal for those outside the US and I'm from Germany.

Nevertheless, I've already completed all the work to push out an update on the day I'm accepted into the program.

I'll post a message here as soon as I see the email.

**Comment by Lunix-420** [comment] 2024-05-03 15:06
Apple somehow managed to bill me a second time for the developer account enrollment, and yet, they still haven't processed it. 

I reached out to their support team yesterday about this, so let's hope they answer soon. This whole situation is just frustrating beyond belief.

I hate how Apple treats their developers. It's like they make everything unnecessarily complicated and then take forever to sort out their own mess.

**Comment by Lunix-420** [comment] 2024-05-08 16:17
Great news!

I've been approved for the Apple Developer Program, and I've just published a signed and notarized version of the latest pre-release.

It's downloadable from: https://github.com/Dimethoxy/Plasma/releases/tag/1.1.0

I've quickly tested it within a virtual machine, and it launched flawlessly without any errors or requiring any workarounds. However, I'd deeply appreciate any feedback you can provide in case it doesn't for you.

Once I gather more concrete evidence of it's functionality, I'll compile and release the final 1.1.0 build.

**Comment by Lunix-420** [comment] 2024-05-08 16:18
Closing this was not planned, I just clicked the wrong button 🥲

**Comment by Lunix-420** [comment] 2024-05-09 16:00
This is should definitely be fixed in the [latest release](https://github.com/Dimethoxy/Plasma/releases/tag/v1.1.0).
If you encounter similar issues in the future, please don't hesitate to open a new issue so we can promptly resolve them.

**Closed as completed by Lunix-420** 2024-05-09 16:00 UTC
Labels: bug, question

**Comment by dev-tb** [comment] 2024-05-09 16:32
Thanks! I’ve donated to help you cover the cost, as promised. I hope more people will do.

**Comment by Lunix-420** [comment] 2024-05-09 17:02
Thanks a ton for your donation! Glad you're enjoying Plasma!
